Repository dRAGon-Okinawa/dRAGon, pull requests merged in 2024-08, with the labels that each got.

#244 Semver version incrementer
  .github/workflows/build.yml
Labels: enhancement

#245 Fix contains
  .github/workflows/build.yml
Labels: enhancement

#246 chore: Update GitHub CLI command to fetch all pull requests in build …
  .github/workflows/build.yml
Labels: enhancement

#250 chore: Update GitHub CLI command to fetch all pull requests in build …
  .github/workflows/build.yml
Labels: documentation, enhancement

#251 Semver version incrementer
  .github/workflows/build.yml
Labels: enhancement

#255 chore: Update build workflow to include push tag and create release
  .github/release.yaml
  .github/workflows/build_deploy.yml
  .github/workflows/label_check.yml
  renovate.json
Labels: cicd

#256 chore: Update build workflow to include push tag and create release
  .github/release.yaml
  .github/workflows/build_deploy.yml
  .github/workflows/label_check.yml
  renovate.json
Labels: cicd
