Repository dRAGon-Okinawa/dRAGon, pull requests merged in 2024-09, with the labels that each got.

#258 UI for Silo Management
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  backend/build.gradle
  backend/src/main/java/ai/dragon/config/WebConfig.java
  backend/src/main/java/ai/dragon/controller/api/backend/repository/AbstractCrudBackendApiController.java
  backend/src/main/java/ai/dragon/controller/api/backend/repository/SiloBackendApiController.java
  backend/src/main/java/ai/dragon/dto/api/DataTableApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/GenericApiData.java
  backend/src/main/java/ai/dragon/dto/api/GenericApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/SuccessApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/TableApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/auth/LoginAuthAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/auth/UserInfoAuthAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/dashboard/NumbersDashboardAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/backend/PagerTableApiData.java
  backend/src/main/java/ai/dragon/dto/api/backend/UUIDsBatchRequest.java
  backend/src/main/java/ai/dragon/repository/util/Pager.java
  backend/src/main/java/ai/dragon/util/UUIDUtil.java
  backend/src/test/java/ai/dragon/controller/api/backend/repository/SiloBackendApiControllerTest.java
  backend/src/test/java/ai/dragon/dto/api/DataTableApiResponseTest.java
  backend/src/test/java/ai/dragon/util/UUIDUtilTest.java
  frontend/mockoon_dRAGon.json
  frontend/package.json
  frontend/packages/axios/package.json
  frontend/packages/scripts/package.json
  frontend/src/assets/svg-icon/mdi--arrow-down-drop-circle-outline.svg
  frontend/src/assets/svg-icon/mdi--arrow-down-drop.svg
  frontend/src/assets/svg-icon/mdi--lead-pencil.svg
  frontend/src/assets/svg-icon/mdi--trash-can-outline.svg
  frontend/src/components/custom/kv-settings.vue
  frontend/src/components/custom/soybean-avatar.vue
  frontend/src/components/custom/split-dropdown.vue
  frontend/src/constants/business.ts
  frontend/src/hooks/common/table.ts
  frontend/src/locales/langs/en-us.ts
  frontend/src/router/elegant/imports.ts
  frontend/src/router/elegant/routes.ts
  frontend/src/router/elegant/transform.ts
  frontend/src/service/api/app-auth.ts
  frontend/src/service/api/app-dashboard.ts
  frontend/src/service/api/backend-silo.ts
  frontend/src/typings/api.d.ts
  frontend/src/typings/app.d.ts
  frontend/src/typings/components.d.ts
  frontend/src/typings/elegant-router.d.ts
  frontend/src/typings/naive-ui.d.ts
  frontend/src/views/infrastructure/silo-detail/[id].vue
  frontend/src/views/infrastructure/silo-list/index.vue
  frontend/src/views/infrastructure/silo-list/modules/silo-edit.vue
  frontend/src/views/infrastructure/silo-list/modules/silo-search.vue
  frontend/src/views/infrastructure/silo-list/modules/user-operate-drawer.vue
  frontend/src/views/infrastructure/silo-list/modules/user-search.vue
  static/tour/dragon-infrastructure-silos.jpg
Labels: enhancement

#259 UI for Silo Management (#258)
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  backend/build.gradle
  backend/src/main/java/ai/dragon/config/WebConfig.java
  backend/src/main/java/ai/dragon/controller/api/backend/repository/AbstractCrudBackendApiController.java
  backend/src/main/java/ai/dragon/controller/api/backend/repository/SiloBackendApiController.java
  backend/src/main/java/ai/dragon/dto/api/DataTableApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/GenericApiData.java
  backend/src/main/java/ai/dragon/dto/api/GenericApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/SuccessApiResponse.java
  backend/src/main/java/ai/dragon/dto/api/TableApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/auth/LoginAuthAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/auth/UserInfoAuthAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/app/dashboard/NumbersDashboardAppApiData.java
  backend/src/main/java/ai/dragon/dto/api/backend/PagerTableApiData.java
  backend/src/main/java/ai/dragon/dto/api/backend/UUIDsBatchRequest.java
  backend/src/main/java/ai/dragon/repository/util/Pager.java
  backend/src/main/java/ai/dragon/util/UUIDUtil.java
  backend/src/test/java/ai/dragon/controller/api/backend/repository/SiloBackendApiControllerTest.java
  backend/src/test/java/ai/dragon/dto/api/DataTableApiResponseTest.java
  backend/src/test/java/ai/dragon/util/UUIDUtilTest.java
  frontend/mockoon_dRAGon.json
  frontend/package.json
  frontend/packages/axios/package.json
  frontend/packages/scripts/package.json
  frontend/src/assets/svg-icon/mdi--arrow-down-drop-circle-outline.svg
  frontend/src/assets/svg-icon/mdi--arrow-down-drop.svg
  frontend/src/assets/svg-icon/mdi--lead-pencil.svg
  frontend/src/assets/svg-icon/mdi--trash-can-outline.svg
  frontend/src/components/custom/kv-settings.vue
  frontend/src/components/custom/soybean-avatar.vue
  frontend/src/components/custom/split-dropdown.vue
  frontend/src/constants/business.ts
  frontend/src/hooks/common/table.ts
  frontend/src/locales/langs/en-us.ts
  frontend/src/router/elegant/imports.ts
  frontend/src/router/elegant/routes.ts
  frontend/src/router/elegant/transform.ts
  frontend/src/service/api/app-auth.ts
  frontend/src/service/api/app-dashboard.ts
  frontend/src/service/api/backend-silo.ts
  frontend/src/typings/api.d.ts
  frontend/src/typings/app.d.ts
  frontend/src/typings/components.d.ts
  frontend/src/typings/elegant-router.d.ts
  frontend/src/typings/naive-ui.d.ts
  frontend/src/views/infrastructure/silo-detail/[id].vue
  frontend/src/views/infrastructure/silo-list/index.vue
  frontend/src/views/infrastructure/silo-list/modules/silo-edit.vue
  frontend/src/views/infrastructure/silo-list/modules/silo-search.vue
  frontend/src/views/infrastructure/silo-list/modules/user-operate-drawer.vue
  frontend/src/views/infrastructure/silo-list/modules/user-search.vue
  static/tour/dragon-infrastructure-silos.jpg
Labels: skip-changelog

#267 chore: Update dependencies in build.gradle and package.json
  backend/build.gradle
  build.gradle
  frontend/package.json
Labels: dependency, patch

#268 chore: Update build workflow to include push tag and create release (…
  .github/workflows/build_deploy.yml
  build.gradle
Labels: patch

#269 Fix pnpm set version force
  .github/workflows/build_deploy.yml
Labels: skip-changelog, patch

#270 feat: Add custom form item component with help tooltip
  frontend/package.json
  frontend/src/assets/svg-icon/mdi--question-mark-circle-outline.svg
  frontend/src/components/custom/form-item-with-help.vue
  frontend/src/components/custom/tag-renderer.vue
  frontend/src/locales/langs/en-us.ts
  frontend/src/typings/app.d.ts
  frontend/src/typings/components.d.ts
  frontend/src/views/infrastructure/farm-list/modules/farm-edit.vue
Labels: documentation, patch

#272 feat: Add tests for ExtendedFluentFilter and ExtendedRegexFilter classes
  .github/release.yaml
  .github/workflows/label_check.yml
  backend/src/main/java/ai/dragon/job/silo/ingestor/loader/URLIngestorLoader.java
  backend/src/test/java/ai/dragon/util/db/filters/ExtendedFluentFilterTest.java
  backend/src/test/java/ai/dragon/util/db/filters/ExtendedRegexFilterTest.java
Labels: test

#288 Update Frontend & Backend dependencies
  backend/build.gradle
  build.gradle
  frontend/package.json
Labels: dependency, patch
